// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * http://mxdev.meicloud.com/mx-native-docs/?id=19
 * @returns {Promise.<MxObject>}
 */
export async function webview() {
	// BEGIN USER CODE
	return new Promise(function (resolve, reject) {
    window.cordova.exec(function (success) {
      mx.data.create({
        entity: "MideaCommon.WebviewResponse",
        callback: function (mxObject) {
          mxObject.set("webviewWidth", success.webviewWidth);
          mxObject.set("webviewHeigh", success.webviewHeigh);
          resolve(mxObject);
        },
        error: function (e) {
          reject("Could create object:" + error.message);
        }
      });
    }, function (error) {
      reject("Error: " + error);
    }, "MideaCommon", "webview", []);

  });
	// END USER CODE
}
